on: 
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]
name: ci/github

permissions:
  contents: read

jobs:
  unit:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Unit Test
      run: make test
  e2e:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0
      with:
        config: test/e2e/kind/config.yaml
        cluster_name: kubearchive-testing
        version: v0.15.0
        kubectl_version: v1.25.0
    - name: Set up ingress
      run: make setup-ingress
    - name: Build container image
      run: make container-build IMG=localhost/kubearchive:testing
    - name: Load image into KinD
      run: make container-load-kind KIND=$(which kind) IMG=localhost/kubearchive:testing
    - name: Deploy kubearchive
      run: make deploy IMG=localhost/kubearchive:testing
    - name: E2E test
      run: make test-e2e
